enum BasketActionTypes {
  GET_BASKET,
  GET_BASKET_RESPONSE,

  REGISTER_BASKET,
  REGISTER_BASKET_RESPONSE,

  REMOVE_ITEM_FROM_BASKET,
  REMOVE_ITEM_FROM_BASKET_RESPONSE,

  ADD_TO_BASKET_ACTION,

  GET_SHOES,
  GET_SHOES_RESPONSE
}

export default BasketActionTypes;