enum BasketActionTypes {
  REMOVE_FROM_BASKET,
  GET_BASKET_RESPONSE,
  REGISTER_BASKET,
  REGISTER_BASKET_RESPONSE,
  REMOVE_ITEM_FROM_BASKET,
  REMOVE_ITEM_FROM_BASKET_RESPONSE,
}

export default BasketActionTypes;